### ISSUE TITLE
chd files

### ISSUE THREAD

**Issue by renegadeangel** [autobleem/AutoBleem#234]
I converted a psx game, Wipeout containing .bin files into a chd file and save around 30% in file size. 

I could load the game via "Load Content" then select the PSX emulator (NEON) but I cannot get frontend to see the chd even though I added it to the playlist file for autobleem.

Will a fix be found or am I doing something wrong. The chd is in the Games folder.

**Comment by screemerpl** [comment]
We do not support CHD in Autobleem, but you can use PBP for even better results in size reduction (we support playstation portable POPStation PBP files). Well known PSX2PSP is your tool for converting your binary images to PBP format.

**Comment by renegadeangel** [comment]
Thanks for the replay..

Is there a reason it is not supported as it does work fine when loaded through "Load Content".

Is it not a simple task of adding "chd" to the compatable extensions if looks for, like it does with PBP?

**Comment by screemerpl** [comment]
CD image compression always hits the performance. We added  PBP support already, but you may have some drops in framerate when there is data transfer from iso file. We recommend to use cue/bin for best compatibility, and if you really want to compress game images use PSX2PSP and create PBP files (it works but as I said not recommended). Currently we do not plan to support CHD in autobleem UI. You can still probably be able to use them with retroboot/retroarch.
