### ISSUE TITLE
Strange bug?

### ISSUE THREAD

**Issue by renegadeangel** [autobleem/AutoBleem#235]
I played WipEout by selecting the game using "X". the music played in the game.

When I selected the game using "square button" there is no music playing.

When I did a test with a chd file it did play the music via the Retroarch core PSX (NEON)

Any ideas?

**Comment by Steve-Ercel** [comment]
I was looking for this issue! It happens to me too when playing Mickey's Wild Adventure. When playing in Retroarch itself it doesn't happen. 

Now I don't want to use Autobleem anymore, wich is a shame. I love the square button feature. I hope this gets fixed.

**Comment by screemerpl** [comment]
Will be fixed on next release.
https://youtu.be/5YcpbaNa5r0 
Here is video showing the fix. Im closing this
