### ISSUE TITLE
Have to scan games every bootup

### ISSUE THREAD

**Issue by bwayne388** [autobleem/AutoBleem#260]
Since I updated to 0.8.0 every time I boot up my PS Classic it ask me to re-scan my games.

**Comment by ChocoNutDancer** [comment]
Look in the file autobleem/bin/autobleem/gamesThatFailedVerifyCheck.txt.  If you have any invalid games delete them.

**Comment by bwayne388** [comment]
Thank you so much, that did the trick.  I didn't know about the txt file and thought I was going to have to go through each game.
