### ISSUE TITLE
.cue filename 64 char limit

### ISSUE THREAD

**Issue by IgoSplashman** [autobleem/AutoBleem#261]
I was having an odd issue with a couple of games that just wouldn't launch after freshly installing Autobleem 0.8 on my new PSC. As soon as the games were properly added them to the regional list, trying to launch them would show me the empty GUI with the game title on the bottom for a couple of seconds and then jump back into the game selection with an `OOPS! Game crashed. Resume point not available`-error message at the top.

Some of the games in question that refused to launch were:
- `Castlevania - Symphony Of The Night [Quality Patch 1.2][NTSC-U][SLUS-00067]`
- `Final Fantasy I & II (Final Fantasy Origins) [NTSC-U][v1.1][SLUS-01541]`
- `Marl Oukoku no Ningyou Hime 2 - Little Princess [NTSC-J][Disc 1 Main] [SLPS-03012]`
- `Strider Hiryuu 1 & 2 [NTSC-J] (Strider Hiryuu) [Disc 2] [SLPS-02620]`
- `Tetris with Card Captor Sakura - Eternal Heart [NTSC-J][SLPS-02886]`

A couple of tests showed that they launched just fine in Bleemsync and RetroArch. So I tried many different things such as reinstalling, reformatting to different file systems, renaming the files without special characters, changing emulators, etc...

Just as the issue was driving me near crazy, it turned out to have a very simple cause:
For some reason, **Autobleem does not like .cue files longer than 64 characters.** Shortening any of the games above to less than 64 characters completely resolves it.

For example:
- `Tetris with Card Captor Sakura - Eternal Heart [NTSC-J] [SLPS-02886].cue` (69 chars) does not launch
- `Tetris with Card Captor Sakura [NTSC-J] [SLPS-02886].cue` (53 chars) does launch.

It also appears that only .cue files are affected, as the game will still launch even if .bin filenames linked inside the cues exceed 64 characters.

As you can see, game archivists like me who like to have their files properly named will eventually run into this issue, since filenames formatted as `Title - Subtitle [Region][Disc][Code][etc]` can sometimes get pretty long, especially with Japanese games.

Is it possible to fix this issue, or is it a known limitation of Autobleem? If it's not fixable, Autobleem really should **display a proper warning when .cue files exceed this limit** on the screen / in a log, or just **force rename the files to the accepted limit** so they will at least launch after being added to the database.

**Comment by ChocoNutDancer** [comment]
Thanks for the bug report and for tracking it down to a limit of 64 characters.  I added the issue to my to do list.

**Comment by ChocoNutDancer** [comment]
Since it works fine in Retoarch this could be a problem with the PSC reading the cue file.  And not AB.

**Comment by ChocoNutDancer** [comment]
we have a fix.  I'll make sure we get it into the next release after 0.8.1 which will probably be 0.8.5.

**Comment by ChocoNutDancer** [comment]
update the one in autobleem/bin/emu with this
[pcsx-ab.zip](https://github.com/autobleem/AutoBleem/files/3942780/pcsx-ab.zip)

**Comment by screemerpl** [comment]
Closing - will be fixed in next release

**Comment by IgoSplashman** [comment]
I just got around to test it now and it seems to work. Thanks a bunch!
