### ISSUE TITLE
Failed to Load Data. Error Code: 001-001

### ISSUE THREAD

**Issue by craigerskine** [autobleem/AutoBleem#262]
Just installed a fresh version of AutoBleem 0.8.0.

It boots into the AutoBleem splash screen and says `Games changed. Press X to scan` (everytime I reboot the mini it says `Games changed` even though I have not installed any new games or touched the SD card in any way)

After pressing X is says `Total: 0 games scanned`

If I press Start to launch AutoBleem I get a black screen with a blue box that reads Failed to Load Data. Error Code: 001-001. The only way out of this screen is to turn the mini off/on.

If I set `Quickboot Init: RetroArch` it still boots to the splash screen and never auto starts RetroArch. I can manually launch RetroArch with no problems.

I've tried installing a fresh version 3 times now and I keep getting the same results. I've used Windows 10 and macOS to copy over the files and I get the same result with both.

Is there something I'm missing? Should we not be using this version yet?

**Comment by ChocoNutDancer** [comment]
See if any files are listed in autobleem/bin/autobleem/gamesThatFailedVerifyCheck.txt

**Comment by craigerskine** [comment]
> See if any files are listed in autobleem/bin/autobleem/gamesThatFailedVerifyCheck.txt

The file is empty.

**Comment by ChocoNutDancer** [comment]
when it's doing the scan are game names flashing on the screen as it scans the games?

**Comment by craigerskine** [comment]
No. It says `0 Games scanned` super fast on the screen. Takes less than a second.

**Comment by ChocoNutDancer** [comment]
are you copying 0.8.0 on top of an existing usb build or are you starting with just 0.8.0 on the usb and then copying over your games into /Games?

**Comment by craigerskine** [comment]
I tried an upgrade at first. But this morning I did a fresh install 2 times and all 3 resulted in the exact same behavior.

**Comment by craigerskine** [comment]
If I install 0.7.1 everything works fine.

**Comment by ChocoNutDancer** [comment]
I would love to know how this is happening.  would you be able to post a zip of a single game dir that I could download?  can you post where a picture of what the contents of /games dir looks like?  I need to somehow reproduce this.  are you game files bin's, pbp's?

**Comment by craigerskine** [comment]
I have nothing in my Games folder. I just want to use the default games that are pre-installed on the Classic. This is how I used 0.7.1.

I put my extra PSX games in the roms folder and play them via RetroArch so everything is in one place and one UI. I like my roms organized and all in one place so my roms folder looks like: `atari-2600`, `nintendo-nes`, etc. so everything lines up and all like systems are together.

![image](https://user-images.githubusercontent.com/56437/70337837-71bddb80-1811-11ea-8f80-4f7baf326df3.png)

On 0.7.1 my internal games showed up in a RA playlist, but in 0.8.0 the playlist for internal games is empty.

I mainly use AutoBleem as a RetroArch vessel since it can play most systems decently and is easier to setup and has less issues than a Raspberry Pi and RetroPie.

**Comment by ChocoNutDancer** [comment]
oh you're talking about retroarch games.  that's completely separate from the playstation games in /Games.  the scan that happens is only for the PS1 games in /Games not for the games in the retroarcg roms folder.  you need to copy your playlists files over from your old usb.  there may be another dir to copy over too.  let me see if I can find out what.

**Comment by ChocoNutDancer** [comment]
the thumbnails folder I think.

**Comment by craigerskine** [comment]
Yes, I did all that and RA works decently (sans the internal games not showing up anymore).

However, I used to be able to just use my Classic like it never had AutoBleem installed... this does not work anymore because it does not see any of the internal games (hence the 001-001 error code) regardless of the toggle in settings. I have to remove the AutoBleem SD card and reboot the Classic in order to see the internal games.

Finally, AutoBleem cannot be set to auto boot into RetroArch anymore regardless of the proper settings being applied.

This release seems broken to me.

**Comment by ChocoNutDancer** [comment]
the 0.8.0 release has "Retroboot 0.10.0 for Autobleem" pre-installed with Autobleem.  If you don't want Autobleem at all you should install the standalone version of Retroboot that does not use Autobleem.  it boots directly into Retroboot and you will only see retroarch games.

**Comment by craigerskine** [comment]
I'll try this.

Thanks for the info.

**Comment by ChocoNutDancer** [comment]
https://www.reddit.com/r/PlaystationClassic/comments/e25ae9/release_retroboot_010_standalone_and_retroboot/

**Comment by craigerskine** [comment]
I just tried this and it works a treat! Thanks so much, this is exactly what I wanted!

**Comment by ChocoNutDancer** [comment]
I've fixed the crash error if you have no games in /games.  it'll be in 0.8.1
