### ISSUE TITLE
Failed to Verify!

### ISSUE THREAD

**Issue by Osama964** [autobleem/AutoBleem#333]
It’s my first time to use AutoBleem, I got a Torrent file includes a 104 games for PSC, I’ve done everything good, but when I try to scan for games I got a “Failed to verify game” some games worked good, and other which failed to verify are not showing at all.
Any suggestions on how to solve this?

**Comment by AKA-Axanar** [comment]
look in the System/Logs directory for why the games failed to verify.  consider finding a better set of game files.  you should go to the discord support channel if you need further help.  but do not ask where to get game files.
