### ISSUE TITLE
No way to filter favourites??

### ISSUE THREAD

**Issue by i00** [autobleem/AutoBleem#339]
Pressing select filters between all / Retorarch / apps ... there appears to be no way to show just my favourites?

**Comment by AKA-Axanar** [comment]
press L2+Select to show favorites and other subcategories.  if you have further questions please go to the autobleem support channel on discord.

**Comment by i00** [comment]
Ok thanks ... didn't realise that there was a way to do this since the odious filter is for retroarch / apps
