### ISSUE TITLE
PS4 Controller wont work with Autobleem 0.9 and 8Bitdo USB donlge

### ISSUE THREAD

**Issue by cliffyb73** [autobleem/AutoBleem#343]
I bought a 8bitdo usb wireless dongle for the PS classic so I can use my PS4 pad. I plugged it in snyced it up and then the main autobleem screen asked to to configure my controller. It's fine until I try to configure either L2 or R2. I press them and nothing happens. They wont work in game either. 

Weirdly they pick up fine in Retroarch and I have no problems with that but its no good if i cant use it with autobleem. 

It also sees it as a xbox controller too rather than a ps4.

Has anyone else had this issue?

Cheers.

**Comment by AKA-Axanar** [comment]
notv37 answered this on the discord support channel and I'm copying his answer here.

The 8bitdo is in xinput mode. You need to put it in macos mode.  https://discordapp.com/channels/538848850840911882/538848850840911890/713154496712147015
